[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
controller = "657mUtzd2sXVVEixmWbkVGN1Fmw7qYLed26D7tYvNLzt"
factory = "AHEMjmhS67VivxocceVtTQRt6ytXKmH8AFJFWtN3cn2q"
members = "3zPRbygSbahvyrTHjvNyxmAVZh1qrAa3svDcbu4LWzxP"

[programs.devnet]
controller = "657mUtzd2sXVVEixmWbkVGN1Fmw7qYLed26D7tYvNLzt"
factory = "AHEMjmhS67VivxocceVtTQRt6ytXKmH8AFJFWtN3cn2q"
members = "3zPRbygSbahvyrTHjvNyxmAVZh1qrAa3svDcbu4LWzxP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test_errors = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/04-factory_errors.ts"
