[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
controller = "3pVBN6dAvQMp7xG73t2y2isiEcZGqkyjXkySW6SdrG6v"
factory = "6oJjbaBrFFzcy4h5Qt7pffLTyF737rv5W6uUbcdz98T6"
members = "2JzLi3jJyQrXSDGY1AVbwWxbGZM29DeodKMCzABhhpJu"

[programs.devnet]
controller = "3pVBN6dAvQMp7xG73t2y2isiEcZGqkyjXkySW6SdrG6v"
factory = "6oJjbaBrFFzcy4h5Qt7pffLTyF737rv5W6uUbcdz98T6"
members = "2JzLi3jJyQrXSDGY1AVbwWxbGZM29DeodKMCzABhhpJu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test_errors = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/04-factory_errors.ts"
