[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
controller = "GTkcUnQCncDf24pwxkksGNuo9PrVFY2YFkiN8u922XSp"
factory = "Fii8GURTsfPZrpBZNd99BRPMDztUUGm7Th1XfoANDHVh"
members = "HxdhCwohSbt23EHpHH2yzub82nkdmZP69NFrXwyUe2cU"

[programs.devnet]
controller = "GTkcUnQCncDf24pwxkksGNuo9PrVFY2YFkiN8u922XSp"
factory = "Fii8GURTsfPZrpBZNd99BRPMDztUUGm7Th1XfoANDHVh"
members = "HxdhCwohSbt23EHpHH2yzub82nkdmZP69NFrXwyUe2cU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test_errors = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/04-factory_errors.ts"
